[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>	'''

[window]
opacity = 1
decorations = "none"

[window.padding]
x = 10
y = 10

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic" 

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0
